from datetime import datetime, time, date, timedelta
now  = datetime.now()
print(now)
print(now.year)
print(now.month)
print(now.day)
print(now.hour)
print(now.minute)
print(now.second)
print(now.timestamp())
print("===========================")
year_2023 = datetime(2023, 12, 31)
print(year_2023)
print(year_2023.year)
print(year_2023.second)
print(year_2023.timestamp())
print("===========================")
current_time = time(21,6,22)
print(current_time)
print(current_time.hour)
print(current_time.minute)
print(current_time.second)
print("===========================")
current_date = date(2022,12,2)
print(current_date)
print(current_date.year)
print(current_date.month)
print(current_date.day)
current_date = date(current_date.year + 1,current_date.month - 1,current_date.day + 1)
print(current_date)
print("===========================")
diff = year_2023 - now
print(diff)
print("===========================")
start_time_delta = timedelta(100,200,300, weeks=20)
end_time_delta = timedelta(200,100,400, weeks=10)
print(start_time_delta - end_time_delta)